logging:
  level.*:
    org.springframework.web.client.RestTemplate: DEBUG
    com.crypto: DEBUG
  file:
    name: logs/trading-crypto.log

server:
  port: 8091
  servlet:
    context-path: /crypto
spring:
  datasource:
    url: ${SPRING_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASS}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



crypto-api:
  coinmarketcap: 5e326a7d-41e5-4604-85d5-0e4a21712753
  coincgecko: https://api.coingecko.com/api/v3/coins/markets

error-internal-mail:
  active: true
  address: denemespringdeneme@gmail.com

cache:
  expire:
    time: 5
