logging:
  level.*:
    org.springframework.web.client.RestTemplate: DEBUG
    com.kandilliapi.earthquakekandilli: DEBUG
  file:
    name: logs/sentiment-analyzer

server:
  port: 8094
  servlet:
    context-path: /sentiment-analyzer

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pass
cache:
  expire:
    time: 5
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
